apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config-{{ .Values.deployment.app.name }}
  namespace: {{ .Values.namespace }}
data:
  config.json: |
    {
      "APP_SUB_PATH": "/{{ .Values.namespace }}"
    }
