service:
  port:
    name: http
    l4_protocol: TCP
    port: 80
    targetPort: 80
  label: frontend-service-2-yauyrvhbjq
  name: frontend-service-2-yauyrvhbjq
  selector: frontend-service-2-yauyrvhbjq
  type:
  - ClusterIP
  - NodePort
namespace: -@namespace@-
pvc:
  name: pvc-frontend-service-2-yauyrvhbjq
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
deployment:
  app:
    name: frontend-service-2-yauyrvhbjq
    type: angular
  replicas: -@replicas@-
  update:
    type: RollingUpdate
  repo:
    url: -@imageRepoName@-
  image:
    name: frontend-service-2-yauyrvhbjq
    tag: lastest
    secret: -@repoSecret@-
  container:
    name: frontend-service-2-yauyrvhbjq
    port: 80
  volume:
    name: pvc-frontend-service-2-yauyrvhbjq
  resource:
    request:
      memory: -@requestMemory@-
      cpu: -@requestCpu@-
    limits:
      memory: -@limitsMemory@-
      cpu: -@limitsCpu@-
  backing: 
  secret:
    name: []
  configmap:
    name: []
  hpa:
    name: hpa-frontend-service-2-yauyrvhbjq
    minReplicas: -@minReplicas@-
    maxReplicas: -@maxReplicas@-
    cpu: -@cpuAutoScale@-
    memory: -@memAutoScale@-
